development: &defaults
  client_id: 145425388892883
  client_secret: 644fff9eaa2d9cdeb0c9341afa515954
  scope: user_about_me,email,publish_stream
  canvas_url: https://apps.facebook.com/music_quiz_dev/

test:
  <<: *defaults

production:
  <<: *defaults
