development: &defaults
  client_id: 160926967336434
  client_secret: 17d31f21f2417788ad53e2e84f2c3a4a
  scope: user_about_me,email,publish_stream
  canvas_url: https://apps.facebook.com/musicquiz_mp/

test:
  <<: *defaults

production:
  <<: *defaults
